=== manutepowa/UMH/TW/P3/XSL Angelillo/cuestionario.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="cuestionario" type="tipoCuestionario"/>
	<xsd:complexType name="tipoCuestionario">
		<xsd:sequence>
			<xsd:element name="tema" type="tipoTema" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tipoTema">
		<xsd:sequence>
			<xsd:element name="cuestion" type="tipoCuestion" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="tipoCuestion">
		<xsd:sequence>
			<xsd:element name="fecha" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="autor" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="enunciado" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="respuesta" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="tipo" type="tipoTipo" use="required"/>
		<xsd:attribute name="codigo" type="xsd:ID" use="required"/>
		<xsd:attribute name="varias" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="minimo" type="xsd:int" use="optional"/>
		<xsd:attribute name="maximo" type="xsd:int" use="optional"/>
		<xsd:attribute name="filas" type="xsd:int" use="optional"/>
		<xsd:attribute name="columnas" type="xsd:int" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="tipoTipo">
	    <xsd:restriction base="xsd:string">
	       <xsd:enumeration value="codificada"/>
	       <xsd:enumeration value="numerica"/>
	       <xsd:enumeration value="logica"/>
	       <xsd:enumeration value="texto"/>
	    </xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== manutepowa/UMH/TW/P3/XSL Angelillo/main.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!-- <!DOCTYPE cuestionario SYSTEM "cuestionario.DTD"> -->
<cuestionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cuestionario.xsd">
<!-- <cuestionario> -->
	<tema nombre="informatica">
		<cuestion tipo="logica" codigo="inf1">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				1. El primer sistema operativo fue el Windows 98
			</enunciado>
			<respuesta>Verdadero</respuesta>
			<respuesta>Falso</respuesta>
		</cuestion>

		<cuestion tipo="texto" codigo="inf2" filas="10" columnas="50">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				2. Diferencias entre programacion secuencial y programacion en paralelo
			</enunciado>
			<respuesta></respuesta>
		</cuestion>

		<cuestion tipo="numerica" codigo="inf3" min="10" max="10">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				3. Cual es mi nota en esta practica
			</enunciado>
			<respuesta></respuesta>
		</cuestion>

		<cuestion tipo="codificada" codigo="inf5" varias="no">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				4. Selecciona cual NO es un sistema operativo
			</enunciado>
			<respuesta>
				Linux
			</respuesta>
			<respuesta>
				Solaris
			</respuesta>
			<respuesta>
				OS X
			</respuesta>
			<respuesta>
				HTML
			</respuesta>
		</cuestion>
	</tema>
	<tema nombre="futbol">
		<cuestion tipo="logica" codigo="fut1">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				1. Mourinhio entreno el FC Barcelona
			</enunciado>
			<respuesta>Verdadero</respuesta>
			<respuesta>Falso</respuesta>
		</cuestion>

		<cuestion tipo="texto" codigo="fut2" filas="10" columnas="50">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				2. Ultimo pichichi de la liga inglesa
			</enunciado>
			<respuesta></respuesta>
		</cuestion>

		<cuestion tipo="numerica" codigo="fut3" min="1" max="15">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				3. Numero de copas del rey del Barcelona
			</enunciado>
			<respuesta></respuesta>
		</cuestion>

		<cuestion tipo="codificada" codigo="fut5" varias="si">
			<fecha>
				11/12/2014
			</fecha>
			<autor>
				Angel Fuentes
			</autor>
			<enunciado>
				4. Selecciona los equipos Italiano
			</enunciado>
			<respuesta>
				Elche CF
			</respuesta>
			<respuesta>
				Juventus
			</respuesta>
			<respuesta>
				Ajax
			</respuesta>
			<respuesta>
				Roma
			</respuesta>
		</cuestion>
	</tema>
</cuestionario>
