=== manutepowa/UMH/TW/P3/XLS Nestorin/cuestionario.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="cuestionario" type="tipoCuestionario"/>

	<xsd:complexType name="tipoCuestionario" >
		<xsd:sequence>
			<xsd:element name="tema" type="tipoTema" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="tipoTema">
		<xsd:sequence>
			<xsd:element name="cuestion" type="tipoCuestion" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="nombre" type="xsd:ID" use="required"/> 
	</xsd:complexType>

	<xsd:complexType name="tipoCuestion">
		<xsd:sequence>
			<xsd:element name="enunciado" type="xsd:string"/>
			<xsd:element name="respuesta" type="xsd:string" minOccurs="1" maxOccurs="4"/>
		</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="autor" type="xsd:string" use="optional"/>
			<xsd:attribute name="fecha" type="xsd:string" use="optional"/>
			<xsd:attribute name="minimo" type="xsd:integer" use="optional"/>
			<xsd:attribute name="maximo" type="xsd:integer" use="optional"/>
			<xsd:attribute name="columnas" type="xsd:integer" use="optional"/>
			<xsd:attribute name="filas" type="xsd:integer" use="optional"/>
			<xsd:attribute name="tipo" type="tipoTipo" use="required"/>
			<xsd:attribute name="varias" type="tipoVarias" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="tipoTipo">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Codificada"/>
			<xsd:enumeration value="Numerica"/>
			<xsd:enumeration value="Logica"/>
			<xsd:enumeration value="TextoLibre"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="tipoVarias">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="si"/>
			<xsd:enumeration value="no"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== manutepowa/UMH/TW/P3/cuestionario.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<?xml-stylesheet type="text/css" href="xml.css"?>
<!-- <!DOCTYPE cuestionario SYSTEM "cuestionario.dtd" > -->
<cuestionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="cuestionario.xsd">
	<tema nombre="linux">
		<cuestion tipo="codificada" id="A1" varias="si">
			<enunciado>Cuantas distribuciones de las siguientes son Linux.</enunciado>
			<fecha>12/11/2014</fecha>
			<autor>Manuel Tercero</autor>
			
			<respuesta>Ubuntu</respuesta>
			<respuesta>Debian</respuesta>
			<respuesta>Red Hat</respuesta>
			<respuesta>OX LION</respuesta>
		</cuestion>
		<cuestion tipo="codificada" id="A1" varias="no">
			<enunciado>Cual de las distribuciones son Linux.</enunciado>
			<fecha>12/11/2014</fecha>
			<autor>Manuel Tercero</autor>
			
			<respuesta>Ubuntu</respuesta>
			<respuesta>WINDOWS 7</respuesta>
			<respuesta>WINDOWS</respuesta>
			<respuesta>OX LION</respuesta>
		</cuestion>
		<cuestion tipo="numerica" id="A2" minimo="10" maximo="15">
			<enunciado>Cuantas distribuciones basadas en Debian hay.</enunciado>
			<fecha>12/10/2014</fecha>
			<autor>Manuel Tercero</autor>

			<respuesta></respuesta>
		</cuestion>
		<cuestion tipo="logica" id="A3">
			<enunciado>Red Hat esta basado en Debian?.</enunciado>
			<fecha>14/11/2014</fecha>
			<autor>Manuel Tercero</autor>

			<respuesta>Verdadero</respuesta>
			<respuesta>Falso</respuesta>
		</cuestion>
		<cuestion tipo="codificada" id="A5" varias="no">
			<enunciado>Cual de las siguientes distribuciones no es Linux.</enunciado>
			<fecha>12/11/2014</fecha>
			<autor>Manuel Tercero</autor>
			
			<respuesta>Ubuntu</respuesta>
			<respuesta>Debian</respuesta>
			<respuesta>Red Hat</respuesta>
			<respuesta>Windows RT</respuesta>
		</cuestion>
		<cuestion tipo="texto" id="A4" filas="5" columnas="60">
			<enunciado>Como funciona Visual Studio.</enunciado>
			<fecha>11/11/2014</fecha>
			<autor>Manuel Tercero</autor>
			<respuesta></respuesta>
		</cuestion>
	</tema>
	<tema nombre="windows">
		<cuestion tipo="logica" id="A3">
			<enunciado>Red Hat esta basado en Debian?.</enunciado>
			<fecha>14/11/2014</fecha>
			<autor>Manuel Tercero</autor>

			<respuesta>Verdadero</respuesta>
			<respuesta>Falso</respuesta>
		</cuestion>
		<cuestion tipo="texto" id="A4" filas="10" columnas="12">
			<enunciado>Como funciona Visual Studio.</enunciado>
			<fecha>11/11/2014</fecha>
			<autor>Manuel Tercero</autor>
			<respuesta></respuesta>
		</cuestion>
	</tema>
</cuestionario>
